version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DEBUG: "1"
      DJANGO_DB_HOST: postgres
      DJANGO_DB_PORT: 5432
      DJANGO_DB_NAME: postgres
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: "postgres"

volumes:
  db-data: