name: GitHub Classroom Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: persons
          POSTGRES_USER: program
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Шаг 1: Клонируем репозиторий
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Шаг 2: Установка Python и зависимостей
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r djangoProject/requirements.txt

      # Шаг 3: Установка Yandex Cloud CLI
      - name: Install Yandex Cloud CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "/home/runner/yandex-cloud/bin" >> $GITHUB_PATH
          echo 'export PATH="$PATH:/home/runner/yandex-cloud/bin"' >> ~/.bashrc
          echo "Yandex Cloud CLI installed."

      # Шаг 4: Make migrations
      - name: Make migrations
        run: |
          . venv/bin/activate
          python djangoProject/myproject/manage.py makemigrations

      # Шаг 5: Применение миграций
      - name: Run migrations
        run: |
          . venv/bin/activate
          python djangoProject/myproject/manage.py migrate

      # Шаг 6: Запуск тестов Django
      - name: Run Django Tests
        run: |
          . venv/bin/activate
          python djangoProject/myproject/manage.py test

      # Шаг 7: Аутентификация в Yandex Cloud
      - name: Authenticate to Yandex Cloud
        run: |
          echo '${{ secrets.YC_SERVICE_ACCOUNT_KEY }}' > key.json
          /home/runner/yandex-cloud/bin/yc config set service-account-key key.json
          /home/runner/yandex-cloud/bin/yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          /home/runner/yandex-cloud/bin/yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
          /home/runner/yandex-cloud/bin/yc container registry configure-docker

      # Шаг 8: Сборка Docker-образа приложения
      - name: Build Docker image
        run: |
          docker build -t cr.yandex/${{ secrets.CR_REPOSITORY }}/artemborisov/my-app:${{ github.sha }} .

      # Шаг 9: Сборка Docker-образа для PostgreSQL
      - name: Build PostgreSQL Docker image
        run: |
          docker build -t cr.yandex/${{ secrets.CR_REPOSITORY }}/artemborisov/postgres:${{ github.sha }} -f Dockerfile .

      - name: Verify Docker image exists
        run: |
          docker images cr.yandex/${{ secrets.CR_REPOSITORY }}/artemborisov/my-app:${{ github.sha }}

      # Шаг 10: Публикация образов в Yandex Container Registry
      - name: Push Docker images
        run: |
          docker push cr.yandex/${{ secrets.CR_REPOSITORY }}/artemborisov/my-app:${{ github.sha }}
          docker push cr.yandex/${{ secrets.CR_REPOSITORY }}/artemborisov/postgres:${{ github.sha }}

      # Шаг 11: Деплой приложения и базы данных на существующую машину через SSH
      - name: Deploy to existing Yandex Cloud machine via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 84.201.169.121
          username: artemborisov
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          # Обновление Docker-контейнеров на сервере
          script: |
            docker pull cr.yandex/${{ secrets.CR_REPOSITORY }}/artemborisov/my-app:${{ github.sha }}
            docker pull cr.yandex/${{ secrets.CR_REPOSITORY }}/artemborisov/postgres:${{ github.sha }}

            docker stop my-app || true
            docker rm my-app || true
            docker stop postgres || true
            docker rm postgres || true

            docker run -d --name my-app -p 8080:8080 cr.yandex/${{ secrets.CR_REPOSITORY }}/artemborisov/my-app:${{ github.sha }}
            docker run -d --name postgres -p 5432:5432 cr.yandex/${{ secrets.CR_REPOSITORY }}/artemborisov/postgres:${{ github.sha }}
      

      # Шаг 12: Запуск тестов API через Postman
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: lab1-template/postman/[inst] Lab1.postman_collection.json
          environment: lab1-template/postman/[inst] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      # Шаг 13: Автогрейдинг
      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{ secrets.GOOGLE_API_KEY }}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 1
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
